name: Build
on: push
  
jobs:
 build-X64:
  runs-on: [self-hosted, Linux, X64]
  steps:
  - uses: actions/checkout@v4
  - name: clean
    run: git clean -xdf
  - name: build linux
    run: make -f Makefile.libretro -j 16
  - uses: actions/upload-artifact@v4
    with:
      name: build_linux
      path: mame_libretro.so
  - name: clean
    run: git clean -xdf
  - name: Install mingw
    run: apt-get -y install mingw-w64 mingw-w64-x86-64-dev g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64 
  - name: Build windows
    run: TARGETOS=windows PTR64=1 OVERRIDE_CC=x86_64-w64-mingw32-gcc-posix OVERRIDE_CXX=x86_64-w64-mingw32-g++-posix OVERRIDE_LD=x86_64-w64-mingw32-ld MINGW64=/usr make -f Makefile.libretro -j 16
  - uses: actions/upload-artifact@v4
    with:
      name: build_windows
      path: mame_libretro.dll
 build-Arm64-mac:
  runs-on: [self-hosted, macOS, ARM64]
  steps:
  - uses: actions/checkout@v4
  - name: clean
    run: git clean -xdf
  - name: build mac
    run: make REGENIE=1 VERBOSE=1 NOWERROR=1 OSD=retro NO_USE_MIDI=1 NO_USE_PORTAUDIO=1 PYTHON_EXECUTABLE=python3 CONFIG=libretro DONT_USE_NETWORK=1 TARGETOS=macosx LIBRETRO_OSX_ARM64=1 PLATFORM=arm64 macosx_arm64_clang LIBRETRO_CPU=arm64 PTR64=1 TARGET=mame -j8
  - uses: actions/upload-artifact@v4
    with:
      name: build_mac_arm64
      path: mame_libretro.dylib
